name: easyenglish
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_support_pack: ^1.0.1
  firebase_core: ^1.2.0
  firebase_messaging: ^11.4.2
  firebase_crashlytics: ^2.0.4
  firebase_analytics: ^9.1.10
  firebase_auth: ^3.3.20
  firebase_performance: ^0.8.0+14
  firebase_remote_config: ^2.0.9
  cloud_firestore: ^3.1.18
  flutter_secure_storage: ^5.0.2
  package_info: ^2.0.0
  dio: ^4.0.0
  fresh_dio: ^0.3.1
  dio_cache_interceptor: ^3.0.1
  stacked: ^2.1.6
  stacked_services: ^0.8.6
  provider: ^6.0.3
  get_it: ^7.2.0
  rxdart: ^0.27.0
  image_picker: ^0.8.5+3
  crypto: ^3.0.1
  path_provider: ^2.0.1
  equatable: ^2.0.2
  image_cropper: ^2.0.3
  font_awesome_flutter: ^10.1.0
  cached_network_image: ^3.1.0
  flutter_cache_manager: ^3.1.2
  flutter_blurhash: ^0.7.0
  flutter_inappwebview: ^5.3.2
  pin_code_fields: ^7.1.0
  reactive_forms: ^13.0.0
  animations: ^2.0.0
  animate_do: ^2.0.0
  r_dart_library: ^0.4.1
  collection: ^1.15.0
  infinite_scroll_pagination: ^3.0.1+1
  just_audio: ^0.9.12
  syncfusion_flutter_sliders: ^20.1.60
  percent_indicator: ^4.2.2
  easy_localization: ^3.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.3
  stacked_generator: ^0.7.9

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - lib/assets/langs/
    - assets/raw/a_z_letter_duration.json
    - assets/raw/level_1_unit_1_1.mp3
    - packages/easyenglish/assets/images/bg_button_1.png
    - packages/easyenglish/assets/images/bg_button_2.png
    - packages/easyenglish/assets/images/bg_completion.png
    - packages/easyenglish/assets/images/bg_game_percentage.svg
    - packages/easyenglish/assets/images/bg_hint.png
    - packages/easyenglish/assets/images/bg_hint_fail.png
    - packages/easyenglish/assets/images/dialog/ic_error.png
    - packages/easyenglish/assets/images/dialog/ic_success.png
    - packages/easyenglish/assets/images/ic_achieve_1.svg
    - packages/easyenglish/assets/images/ic_achieve_2.svg
    - packages/easyenglish/assets/images/ic_achieve_3.svg
    - packages/easyenglish/assets/images/ic_achieve_4.svg
    - packages/easyenglish/assets/images/ic_achieve_5.svg
    - packages/easyenglish/assets/images/ic_achieve_6.svg
    - packages/easyenglish/assets/images/ic_arrow_back.png
    - packages/easyenglish/assets/images/ic_arrow_back.svg
    - packages/easyenglish/assets/images/ic_arrow_right.svg
    - packages/easyenglish/assets/images/ic_book.svg
    - packages/easyenglish/assets/images/ic_book_2.svg
    - packages/easyenglish/assets/images/ic_boy.svg
    - packages/easyenglish/assets/images/ic_close.svg
    - packages/easyenglish/assets/images/ic_crown.png
    - packages/easyenglish/assets/images/ic_game_badge.svg
    - packages/easyenglish/assets/images/ic_home.svg
    - packages/easyenglish/assets/images/ic_home_nav.svg
    - packages/easyenglish/assets/images/ic_lang_si.svg
    - packages/easyenglish/assets/images/ic_listening.svg
    - packages/easyenglish/assets/images/ic_microphone.svg
    - packages/easyenglish/assets/images/ic_music.svg
    - packages/easyenglish/assets/images/ic_padlock.svg
    - packages/easyenglish/assets/images/ic_pause.svg
    - packages/easyenglish/assets/images/ic_play.svg
    - packages/easyenglish/assets/images/ic_question.svg
    - packages/easyenglish/assets/images/ic_refresh.svg
    - packages/easyenglish/assets/images/ic_settings.svg
    - packages/easyenglish/assets/images/ic_song_1.svg
    - packages/easyenglish/assets/images/ic_song_2.svg
    - packages/easyenglish/assets/images/ic_song_3.svg
    - packages/easyenglish/assets/images/ic_song_4.svg
    - packages/easyenglish/assets/images/ic_song_5.svg
    - packages/easyenglish/assets/images/ic_speaker.svg
    - packages/easyenglish/assets/images/ic_star.svg
    - packages/easyenglish/assets/images/ic_successful.svg
    - packages/easyenglish/assets/images/ic_tortoise.svg
    - packages/easyenglish/assets/images/ic_trophy.svg
    - packages/easyenglish/assets/images/img_1.png
    - packages/easyenglish/assets/images/img_2.png
    - packages/easyenglish/assets/images/img_3.png
    - packages/easyenglish/assets/images/img_4.png
    - packages/easyenglish/assets/images/img_4.svg
    - packages/easyenglish/assets/images/img_boy.svg
    - packages/easyenglish/assets/images/img_game_1.png
    - packages/easyenglish/assets/images/img_game_2.png
    - packages/easyenglish/assets/images/img_game_3.png
    - packages/easyenglish/assets/images/img_game_4.png
    - packages/easyenglish/assets/images/img_monkey_1.png
    - packages/easyenglish/assets/images/img_monkey_2.png
    - packages/easyenglish/assets/images/img_monkey_3.png
    - packages/easyenglish/assets/images/img_monkey_4.png
    - packages/easyenglish/assets/images/img_monkey_5.png
    - packages/easyenglish/assets/images/img_monkey_6.png
    - packages/easyenglish/assets/images/img_monkey_7.png
    - packages/easyenglish/assets/images/img_parent.svg
    - packages/easyenglish/assets/images/img_ellipse.svg
    - packages/easyenglish/assets/images/img_polygon.svg
    - packages/easyenglish/assets/images/img_rectangle.svg
    - packages/easyenglish/assets/images/img_triangle.svg
  fonts:
    - family: ciutadella_rounded
      fonts:
        - asset: packages/easyenglish/assets/fonts/ciutadella_rounded/CiutadellaRounded-Bd.ttf
        - asset: packages/easyenglish/assets/fonts/ciutadella_rounded/CiutadellaRounded-BdIt.ttf
        - asset: packages/easyenglish/assets/fonts/ciutadella_rounded/CiutadellaRounded-Lt.ttf
        - asset: packages/easyenglish/assets/fonts/ciutadella_rounded/CiutadellaRounded-LtIt.ttf
        - asset: packages/easyenglish/assets/fonts/ciutadella_rounded/CiutadellaRounded-Md.ttf
        - asset: packages/easyenglish/assets/fonts/ciutadella_rounded/CiutadellaRounded-MdIt.ttf
        - asset: packages/easyenglish/assets/fonts/ciutadella_rounded/CiutadellaRounded-Rg.ttf
        - asset: packages/easyenglish/assets/fonts/ciutadella_rounded/CiutadellaRounded-RgIt.ttf
        - asset: packages/easyenglish/assets/fonts/ciutadella_rounded/CiutadellaRounded-SmBd.ttf
        - asset: packages/easyenglish/assets/fonts/ciutadella_rounded/CiutadellaRounded-SmBdIt.ttf
flr:
  core_version: 3.2.0
  dartfmt_line_length: 80
  assets:
    - lib/assets/images
  fonts:
    - lib/assets/fonts

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
